name: Automerge

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:


  Tests:
    if: ${{ !(github.event_name != 'pull_request' && github.actor == 'dependabot[bot]') }}
    uses: ./.github/workflows/Tests.yml

  Suite:
    if: ${{ !(github.event_name != 'pull_request' && github.actor == 'dependabot[bot]') }}
    uses: ./.github/workflows/Suite.yml

  Automerge:
    needs:
      - Tests
      - Suite
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Automerge dependabot PRs
    permissions:
      contents: write

    steps:

      - name: Auto-merge Dependabot PR
        run: GITHUB_TOKEN='${{ github.token }}' gh pr merge '${{ github.event.pull_request.html_url }}' --squash
