name: Build Tools

on:
  workflow_call:

jobs:
  build-nextpnr-fpga_interchange-exprimental:
    runs-on: ubuntu-latest
    name: Build nextpnt-fpga_interchange-experimental
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          ./.github/scripts/install.sh
          sudo apt update
          sudo apt install -y python3-dev libboost-dev libboost-filesystem-dev libboost-thread-dev libboost-program-options-dev libboost-iostreams-dev libboost-dev libeigen3-dev capnproto
          sudo cp ./third_party/capnproto-java/compiler/src/main/schema/capnp/java.capnp /usr/include/capnp/java.capnp
      
      - name: Build nextpnr-fpga_interchange
        run: |
          cd ./third_party/nextpnr
          cmake . -DARCH=fpga_interchange -DRAPIDWRIGHT_PATH=./third_party/RapidWright -DINTERCHANGE_SCHEMA_PATH
          make
      
      - name: Install nextpnr-fpga_interchange-experimental
        run:
          sudo cp ./third_party/nextpnr/nextpnr-fpga_interchange /usr/bin/nextpnr-fpga_interchange-experimental
