name: CI Tests

on:
  workflow_call:

jobs:

  Run-tests:
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]

    strategy:
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
    steps:

    - name: Install dependencies
      run: |
        apt-get update -qq
        apt install -y git python${{ matrix.python-version }} python3-pip wget curl
        update-alternatives --install /usr/bin/python python /usr/bin/python${{ matrix.python-version }} 1
        update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check formatting
      run: |
        python --version
        pip install yapf==0.31.0
        make format
        test $(git status --porcelain | wc -l) -eq 0 || { git diff; false;  }

    - name: Check license
      run: source .github/workflows/scripts/check_license.sh

    - name: Check python scripts
      run: source .github/workflows/scripts/check_python_scripts.sh

    - name: Prepare env
      run: |
        make env
        make install_symbiflow

    - name: Run tests
      run: |
        source env.sh
        # Testing parameters injection feature
        python3 exhaust.py --parameters parameters.yaml --toolchain vpr --project blinky --build_type parameters --only_required --fail
        # Testing multiple samples
        python3 exhaust.py --build_type multiple-samples --run_config run_configs/multiple_samples.yaml --only_required --fail
        # Testing multiple seeds
        python3 exhaust.py --build_type multiple-seeds --run_config run_configs/multiple_seeds.yaml --only_required --fail

    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        path: |
          **/plot_*.svg
